### ISSUE TITLE
Italy job boards

### ISSUE THREAD

**Issue by GuidoPenta** [emredurukn/awesome-job-boards#44]
Hi! I'd like to contribute with some italian job board, how can I do?

Thanks!

**Comment by emredurukn** [comment]
First, you need to fork the project
Then you need to add the job boards you want to add and commit.
Finally, you need to make a pull request.

If you write the job boards you want to add directly from here, I can add them too.

**Comment by GuidoPenta** [comment]
Ok, thanks! I've forked the project, I'm learning how to use Github properly and I'd like to add, commit and make a PR if it's good for you :)

**Comment by emredurukn** [comment]
I approved your PR. Thanks for your contribution.
