### ISSUE TITLE
Add VietnamDevs to the list

### ISSUE THREAD

**Issue by henryonsoftware** [emredurukn/awesome-job-boards#82]
Hi, I'm the founder of https://vietnamdevs.com - A hand-pick software engineer job board for English speaker in Vietnam.

Can you help to add it to the Asia list?
Btw, the https://www.techjobsasia.com/ is dead. I think we should remove it.

**Comment by emredurukn** [comment]
Hello, thank you for your suggestion, I made the changes you mentioned with the following commit.

https://github.com/emredurukn/awesome-job-boards/commit/22b6cd0003614405697d76a2557fc2c9892b46a6
